{
    core: {
        reset_address: 0x0100_0000,
        #ISA
        enable_rv32m: False,
        enable_rv32a: False,
        enable_extra_csr: True,
        enable_user_mode: False,
        # Debug
        debug_enable: False,
        enable_triggers: False,
        ntriggers: 4
    },
    platform: {
        ncores: 1,
        rom_address: 0x0100_0000,
        coreint_address: 0x1000_0000,
        plic_address: 0x2000_0000,
        plic_nint: 8,
        mport: [0x8000_0000, 22],
        io: [0x4000_0000, 16]
    }
}
