# Bellatrix minimal configuration
{
    core: {
        reset_address: 0x80000000,
    },
    isa: {
        enable_rv32m: False,
        enable_extra_csr: True,
        enable_user_mode: False,
    }
}
