{
    core: {
        reset_address: 0x80000000,
        #ISA
        enable_rv32m: True,
        enable_extra_csr: True,
        enable_user_mode: True,
        # Debug
        debug_enable: False,
        enable_triggers: False,
        ntriggers: 4
    },
    platform: {
        ncores: 1,
        wbports: {
            # address and size using byte addressing
            mport: [0x8000_0000, 22],
            io: [0x1000_0000, 8]
        }
    }
}
